# Generated by Django 3.2.25 on 2024-06-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sandeep',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.FileField(upload_to='')),
            ],
        ),
    ]
