# Generated by Django 3.2.25 on 2024-07-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_sandeep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='student_id',
            new_name='dadd_id',
        ),
    ]
