# Generated by Django 3.2.25 on 2024-07-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_rename_student_id_parent_dadd_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='dadd_id',
            new_name='parent_id',
        ),
    ]
